"""Fixtures shared across the suite."""

from __future__ import annotations

from pathlib import Path

import pytest

CORPUS = Path(__file__).parent.parent / "scripts" / "bench" / "corpus.txt"


@pytest.fixture(scope="session")
def bench_corpus() -> list[str]:
    """The benchmark corpus VINs — a bigger sweep than tests/vin_samples.py.

    Generated by scripts/bench and deliberately not committed, so a test that
    wants it skips rather than fails when it is absent.
    """
    if not CORPUS.exists():
        pytest.skip("benchmark corpus not present (scripts/bench/corpus.txt)")
    return [ln.strip() for ln in CORPUS.read_text().splitlines() if len(ln.strip()) == 17]
