"""The stale-`WMIYearValidChars` divergence class, enumerated from the dump.

`vpic.spvindecode_errorcode` does not compute the per-position valid characters
that drive its suggested-VIN / error-byte / unused-position logic: it reads them
out of the `vpic.wmiyearvalidchars` cache and recomputes only when a
`(wmi, year)` cell has no rows at all. ultravin always recomputes. Every cell
where the cache disagrees with the recompute is therefore a *known, machine-
provable* ultravin-vs-oracle divergence surface — argued in full at
docs/KNOWN_DEVIATIONS.md#stale-wmiyearvalidchars-cache.

`vpic-import --stale-cache-report` diffs every cell of a dump's cache against the
recompute from that same dump's own pattern rows (`ultravin::recompute_valid_chars`,
the decoder's code path). `scripts/stale_cache_cells.json` is the `(wmi, year)`
list distilled from that scan, regenerated by every monthly refresh. This module
turns that list into a verdict on one observed divergence.

**What keeps a decoder bug out of here.** Not the list's independence: it is
derived by running the decoder's own charset code over the dump, so a bug in
`recompute_valid_chars` would move both the list and the decode together. What
bounds the excuse is (a) `answerkey verify`, which re-checks every frozen VIN's
*whole* decode on every PR and is not consulted here at all, (b) the frozen unit
tests in `crates/ultravin/src/errors.rs`, which pin the charset rendering, and
(c) the refresh's jump gate, which fails a month whose newly-stale cell count
leaps — the shape a charset regression takes. On top of those, what a listed
cell buys is narrow by construction: the divergence must touch only the
error/correction elements the cache feeds, must land on the very cell that VIN's
decode reads (`fVinWMI` + the model year the decode chose), and must point at a
VIN position the cache and the recompute actually disagree at. Anything wider —
a different vehicle, a different model year, a different position — stays a bug,
or stays registered per VIN in `scripts/known_problems.json`.

**Why the printed positions are not the whole class.** The cache feeds
`spvindecode_errorcode`, and that proc does more with the charsets than print
them: it counts how many positions failed, and the count picks which branch
renders the result (one error prints a resolved character, several print `!`
with the full charsets) and which model year the surrounding `spvindecode`
settles on. A single stale position can therefore re-render positions that are
not stale and years that are not wrong, and no containment test over the
*printed* positions can ever recognise that — the evidence has been laundered by
the time it reaches the diff.

`counterfactual_rows` settles those the only way that is sound: by running the
experiment. Freshen the oracle's cache — the proc's own
`fExtractValidCharsPerWmiYear`, the function the cache is a stale materialisation
of — re-decode, and excuse the VIN only if the freshened oracle now reproduces
ultravin byte for byte. No modelling of the branch logic, no position arithmetic,
and fail-closed by construction: anything the freshened oracle still disagrees
about is, by definition, not explained by the cache.
"""

from __future__ import annotations

import argparse
import functools
import json
import re
import sys
from pathlib import Path
from typing import Any

from scripts.parity.normalize import ERROR_ELEMENTS, diff_rows, fingerprint, from_oracle, ultravin_rows

ROOT = Path(__file__).resolve().parents[2]
CELLS = ROOT / "scripts" / "stale_cache_cells.json"

# The counters `vpic-import --stale-cache-report` summarises a scan with.
SUMMARY_FIELDS = (
    "stale_cells",
    "rows_only_in_cache",
    "rows_only_in_recompute",
    "cells_recompute_empty",
    "cache_exception_wmis",
)
MONTH_RE = re.compile(r"^\d{4}_(0[1-9]|1[0-2])$")

ABOUT = (
    "Every (wmi, year) cell of vpic.wmiyearvalidchars whose contents contradict the recompute from "
    "the same dump's pattern rows, with the VIN positions they disagree at — the oracle reads the "
    "cache, ultravin recomputes, so each [wmi, year, positions] entry is a documented divergence "
    "surface confined to those positions of the error/correction elements. Generated from "
    "`vpic-import --stale-cache-report` by every monthly refresh (scripts/refresh.py); never hand-edited, "
    "and never derived from observed output. Policy: docs/KNOWN_DEVIATIONS.md#stale-wmiyearvalidchars-cache."
)


# --------------------------------------------------------------------------- the list


def cells_document(report: dict[str, Any]) -> dict[str, Any]:
    """The committed cell list distilled from a `--stale-cache-report` scan.

    Each entry is `[wmi, year, positions]`: the VIN positions where that cell's
    cache and recompute disagree, in either direction. Positions are what makes
    the excuse this list grants narrow — a cell stale at position 11 explains
    nothing about a difference printed for position 5.
    """
    positions: dict[tuple[str, int], set[int]] = {}
    for cell in report["stale_cells"]:
        at = positions.setdefault((cell["wmi"], int(cell["year"])), set())
        at.update(int(p["position"]) for side in ("only_in_cache", "only_in_recompute") for p in cell[side])
    return {
        "_about": ABOUT,
        "dump": report["dump"],
        "summary": {k: report["summary"][k] for k in SUMMARY_FIELDS},
        "cells": [[wmi, year, sorted(at)] for (wmi, year), at in sorted(positions.items(), key=lambda kv: kv[0])],
    }


def consistency_errors(doc: dict[str, Any]) -> list[str]:
    """Ways `doc` contradicts itself. Empty means internally consistent.

    A month-over-month *change* in the list is expected and is emphatically not
    an error: the list is a fact about that month's dump, and the refresh PR diff
    is where it documents itself. What must never happen is a list that disagrees
    with the summary printed beside it — that means the file was hand-edited or
    the two halves came from different scans, and every downstream verdict built
    on it is then unfounded.
    """
    out: list[str] = []
    if not MONTH_RE.match(str(doc.get("dump", ""))):
        out.append(f"dump {doc.get('dump')!r} is not a YYYY_MM month")

    summary = doc.get("summary")
    if not isinstance(summary, dict) or tuple(summary) != SUMMARY_FIELDS:
        out.append(f"summary keys {tuple(summary) if isinstance(summary, dict) else summary} != {SUMMARY_FIELDS}")
        summary = {}
    for key, value in summary.items():
        if not isinstance(value, int) or isinstance(value, bool) or value < 0:
            out.append(f"summary[{key}] = {value!r} is not a count")

    cells = doc.get("cells")
    if not isinstance(cells, list):
        return [*out, f"cells is {type(cells).__name__}, not a list"]
    pairs: list[tuple[str, int]] = []
    for cell in cells:
        if not (isinstance(cell, list) and len(cell) == 3 and isinstance(cell[0], str) and isinstance(cell[1], int)):
            out.append(f"cell {cell!r} is not a [wmi, year, positions] entry")
            continue
        at = cell[2]
        if not (isinstance(at, list) and at and all(isinstance(p, int) and not isinstance(p, bool) for p in at)):
            out.append(f"cell {cell[0]} {cell[1]} has positions {at!r}, not a non-empty list of ints")
        elif sorted(set(at)) != at:
            # A cell reaches the list only by differing somewhere, so an empty
            # position list means the entry lost the evidence that admitted it.
            out.append(f"cell {cell[0]} {cell[1]} positions {at!r} are not sorted and unique")
        pairs.append((cell[0], cell[1]))
    if len(set(pairs)) != len(pairs):
        out.append(f"{len(pairs) - len(set(pairs))} duplicate cell(s)")
    if pairs != sorted(pairs):
        out.append("cells are not sorted by (wmi, year)")

    stale = summary.get("stale_cells")
    if isinstance(stale, int) and stale != len(cells):
        out.append(f"summary.stale_cells = {stale} but the list holds {len(cells)} cells")
    empty = summary.get("cells_recompute_empty")
    if isinstance(empty, int) and isinstance(stale, int) and empty > stale:
        out.append(f"summary.cells_recompute_empty = {empty} exceeds stale_cells = {stale}")
    rows = summary.get("rows_only_in_cache", 0) + summary.get("rows_only_in_recompute", 0)
    if isinstance(stale, int) and isinstance(rows, int) and rows < stale:
        # A stale cell differs by at least one (position, char) row in one
        # direction, so the two row counters can never sum to less than the cells.
        out.append(f"{rows} differing cache rows cannot account for {stale} stale cells")
    return out


def render_cells(doc: dict[str, Any]) -> str:
    """`doc` as the committed file's text: one cell per line, so the diff reads."""
    body = ",\n".join(f"  {json.dumps(cell)}" for cell in doc["cells"])
    head = ",\n".join(f" {json.dumps(k)}: {json.dumps(doc[k])}" for k in ("_about", "dump", "summary"))
    return "{\n" + head + ',\n "cells": [\n' + body + ("\n" if body else "") + " ]\n}\n"


def write_cells(report: dict[str, Any], path: Path = CELLS) -> dict[str, Any]:
    """Regenerate the committed cell list from a scan report; return the document."""
    doc = cells_document(report)
    Path(path).write_text(render_cells(doc))
    return doc


@functools.cache
def load_cells(path: Path = CELLS) -> dict[tuple[str, int], frozenset[int]]:
    """The committed cells: `(wmi, year)` -> the VIN positions it is stale at."""
    doc = json.loads(Path(path).read_text())
    return {(wmi, int(year)): frozenset(at) for wmi, year, at in doc["cells"]}


# --------------------------------------------------------------------------- the verdict


def vin_wmi(vin: str) -> str:
    """`vpic.fVinWMI`: positions 1-3, plus 12-14 when position 3 is `9`.

    The cache is keyed by exactly this string, so the cell a VIN's decode reads
    is keyed by it too. Port of `vpic/procs/fvinwmi.sql`, mirroring
    `crates/ultravin/src/wmi.rs` (which is what a decode result's `wmi` is).
    """
    v = vin.strip().upper()
    wmi = v[:3] if len(v) > 3 else v
    if wmi[2:3] == "9" and len(v) >= 14:
        wmi += v[11:14]
    return wmi


def cell_for(vin: str, decoded: dict[str, Any] | None = None) -> tuple[str, int] | None:
    """The `(wmi, year)` cache cell `spvindecode_errorcode` reads for this decode.

    The year is the model year the decode settled on — the same one the proc
    passes as `modelYear`. `None` when the decode chose no year at all, which is
    no cell and therefore never this class.
    """
    if decoded is None:
        decoded = _decode(vin)
    year = decoded.get("model_year")
    if not isinstance(year, int) or isinstance(year, bool):
        return None
    return (vin_wmi(vin), year)


def stale_positions(
    vin: str,
    decoded: dict[str, Any] | None = None,
    cells: dict[tuple[str, int], frozenset[int]] | None = None,
) -> frozenset[int]:
    """VIN positions the cell this decode reads is stale at; empty if it is not."""
    cell = cell_for(vin, decoded)
    if cell is None:
        return frozenset()
    return (load_cells() if cells is None else cells).get(cell) or frozenset()


def is_known_stale_cell(
    vin: str,
    decoded: dict[str, Any] | None = None,
    cells: dict[tuple[str, int], frozenset[int]] | None = None,
) -> bool:
    """True when this VIN's decode reads a cell the scan found stale."""
    return bool(stale_positions(vin, decoded, cells))


def diff_view(record: dict[str, Any]) -> dict[str, Any]:
    """The complete diff description inside a divergence record.

    Sweep examples and campaign backlog rows truncate their `field_diffs` list;
    a `fingerprint` (campaign, sweep, and the frozen corpus's `expected_diff`)
    never does. Prefer it, or a truncated wide diff could pass for a narrow one.
    """
    whole = record.get("fingerprint")
    return whole if isinstance(whole, dict) else record


def _element_id(row: Any) -> Any:
    """The element id of one diff row, whichever shape it arrived in.

    `{"element_id": n, ...}` from sweep/campaign, `[n, ...]` from a fingerprint,
    and a bare `n` from the campaign backlog's missing/extra lists.
    """
    if isinstance(row, dict):
        return row.get("element_id")
    if isinstance(row, (list, tuple)):
        return row[0] if row else None
    return row


def error_fields_only(diff: dict[str, Any]) -> bool:
    """True when every difference lands on an element the stale cache can move.

    The cache feeds `spvindecode_errorcode` and nothing else, and that proc's
    output is elements 142/143/144/156/191. A diff that reaches any other
    element — or that changes the GroupName-rank order — is a wider disagreement
    than this defect explains, whichever cell the VIN lands in.

    Fails closed: a record carrying no diff description at all is not judged
    narrow, it is not judged.
    """
    diff = diff_view(diff)
    rows: list[Any] = []
    for key in ("field_diffs", "missing", "extra"):
        part = diff.get(key)
        if part is None:
            return False
        rows += list(part)
    if not rows or diff.get("order_ok", True) is False:
        return False
    return all(_element_id(r) in ERROR_ELEMENTS for r in rows)


# One element-144 group, `(VIN position:allowed chars)`. The proc builds it as
# `'(' || i || ':' || x || ')'` with `i` the 1-based VIN position it is scanning,
# so these numbers are directly comparable with the cell list's positions.
_POSSIBLE_VALUES_GROUP = re.compile(r"\((\d+):([^)]*)\)")


def _possible_values(text: Any) -> dict[int, str]:
    """An element-144 rendering as `{position: charset}`; `{}` for a missing side."""
    if not isinstance(text, str):
        return {}
    return {int(p): "".join(sorted(c)) for p, c in _POSSIBLE_VALUES_GROUP.findall(text)}


def _element_144_positions(oracle: Any, mine: Any) -> set[int]:
    """Positions whose possible-values charset differs, either side possibly absent."""
    a, b = _possible_values(oracle), _possible_values(mine)
    return {p for p in a.keys() | b.keys() if a.get(p) != b.get(p)}


def _element_142_positions(oracle: Any, mine: Any) -> set[int]:
    """Positions where the two SuggestedVINs differ.

    `spvindecode_errorcode` reassembles the whole VIN — WMI, the scanned span,
    then the untouched tail — so character *i* is VIN position *i*. When one side
    offered no suggestion at all the strings are not aligned and there is no
    position in the comparison; element 144 carries the positions in that case.
    """
    if not (isinstance(oracle, str) and isinstance(mine, str)) or not oracle or len(oracle) != len(mine):
        return set()
    return {i for i, (a, b) in enumerate(zip(oracle, mine), start=1) if a != b}


# The only two error elements that name a VIN position. 143/156/191 are
# per-decode summaries — an error-code list, the boilerplate error text, the
# unused-position sentence — so they carry no position of their own and can only
# ride along with whatever 142/144 pointed at.
_POSITIONAL_ELEMENTS = {142: _element_142_positions, 144: _element_144_positions}


def _sides(row: Any) -> tuple[Any, Any, Any]:
    """One field-diff row as `(element_id, oracle value, ultravin value)`.

    `{"element_id", "oracle", "ultravin", ...}` from sweep/campaign,
    `[element_id, field, oracle, ultravin]` from a fingerprint.
    """
    if isinstance(row, dict):
        return row.get("element_id"), row.get("oracle"), row.get("ultravin")
    if isinstance(row, (list, tuple)) and len(row) >= 4:
        return row[0], row[2], row[3]
    return _element_id(row), None, None


def _one_sided(row: Any) -> tuple[Any, Any]:
    """A missing/extra row as `(element_id, value)`; value `None` when unrecorded.

    A fingerprint stores `[element_id, value]`; sweep records the variable name
    instead of the value and the campaign backlog stores a bare element id, so
    neither of those offers positional evidence.
    """
    if isinstance(row, dict):
        return row.get("element_id"), row.get("value")
    if isinstance(row, (list, tuple)) and len(row) >= 2:
        return row[0], row[1]
    return _element_id(row), None


def diff_positions(diff: dict[str, Any]) -> set[int]:
    """The VIN positions an observed difference actually points at.

    Empty means the record names no position — which is a verdict of *not* this
    class, not a free pass: a stale cell explains a difference only at the
    positions it is stale at.
    """
    diff = diff_view(diff)
    out: set[int] = set()
    for row in diff.get("field_diffs") or ():
        element_id, oracle, mine = _sides(row)
        if element_id in _POSITIONAL_ELEMENTS:
            out |= _POSITIONAL_ELEMENTS[element_id](oracle, mine)
    for key, oracle_side in (("missing", True), ("extra", False)):
        for row in diff.get(key) or ():
            element_id, value = _one_sided(row)
            if element_id in _POSITIONAL_ELEMENTS:
                pair = (value, "") if oracle_side else ("", value)
                out |= _POSITIONAL_ELEMENTS[element_id](*pair)
    return out


def is_expected_divergence(
    vin: str,
    diff: dict[str, Any],
    decoded: dict[str, Any] | None = None,
    cells: dict[tuple[str, int], frozenset[int]] | None = None,
) -> bool:
    """True when this divergence *is* the documented stale-cache class.

    All three conditions are required, cheapest first (the second needs a
    decode): only error/correction fields differ, at all — that is everything the
    cache can reach; the cell that decode reads is one the scan found stale; and
    *every* position the difference points at is one that cell is actually stale
    at. Containment, not overlap: a cell stale at position 11 explains a wrong
    charset printed for position 11 and nothing about one printed for position 5,
    so a difference spanning both is wider than the cell accounts for and stays a
    bug — the same verdict it would get had position 11 not been involved.

    Fails closed on every axis, the last one included: a record whose difference
    names no position is not this class.

    This is the *printed-position* test, and it is deliberately narrow: it can
    only recognise a divergence the stale charset printed directly. A stale cell
    that changes the error *count* — flipping `spvindecode_errorcode` between its
    single- and multi-error branches, or moving the model year the decode
    settles on — re-renders positions that are not themselves stale, and no
    containment test can pass that. `counterfactual_rows` is the answer to
    those; this one still serves the sweep and campaign runners, which have a
    diff to judge and no oracle to re-run.
    """
    if not error_fields_only(diff):
        return False
    at = diff_positions(diff)
    return bool(at) and at <= stale_positions(vin, decoded, cells)


def _decode(vin: str, year: int | None = None) -> dict[str, Any]:
    # Lazy: reading and checking the list needs no built extension, and
    # scripts/refresh.py imports this module under a bare `python3`.
    import ultravin  # noqa: PLC0415

    # `full=True` only when the rows are wanted: `cell_for` needs the model year
    # and nothing else, and the provenance rows are the expensive half.
    if year is None:
        return ultravin.decode(vin)
    return ultravin.decode(vin, full=True, year=year)


# ------------------------------------------------------------------------ the repin

# `vpic.spvindecode`'s model-year element. Not an error element — the cache
# cannot print it — but the cache can still decide it, so a year flip can be this
# defect one step removed. See `repin_verdict`.
MODEL_YEAR_ELEMENT = 29

COLLAPSED = "collapsed"
NOT_THIS_CLASS = "not-this-class"
PIN_DID_NOT_TAKE = "pin-did-not-take"
NO_YEAR_FLIP = "no-year-flip"


def _as_year(value: Any) -> int | None:
    """`value` as a model year, or `None` if it is not one."""
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, str) and value.strip().isdigit():
        return int(value.strip())
    return None


def oracle_model_year(rows: list[dict[str, Any]]) -> int | None:
    """The model year this oracle response settled on; `None` if it named none."""
    for row in rows:
        if row.get("element_id") == MODEL_YEAR_ELEMENT:
            year = _as_year(row.get("value"))
            if year is not None:
                return year
    return None


def repin_verdict(
    vin: str,
    oracle_rows: list[dict[str, Any]],
    cells: dict[tuple[str, int], frozenset[int]] | None = None,
) -> str:
    """Whether agreeing on the oracle's model year collapses this divergence.

    The cache feeds `spvindecode_errorcode`, and the error byte that proc builds
    is what `spvindecode` uses to pick between candidate model years. A stale
    cell can therefore move element 29 — an element it can never itself print —
    and drag the whole decode with it. `is_expected_divergence` reads the cell
    keyed by *ultravin's* year, which on a flip is the wrong cell entirely, so it
    can only ever say no. This pins ultravin to the year the oracle chose and
    asks whether what is left is confined to the stale positions of the cell
    keyed by the **oracle's** year.

    Four verdicts, and only `COLLAPSED` is an excuse:

    - `NO_YEAR_FLIP` — the oracle named no year, or ultravin already agrees, so
      there is nothing here for a repin to explain.
    - `PIN_DID_NOT_TAKE` — ultravin was asked for that year and chose another.
      The caller-year hint is only the fourth sort key, behind the error code, so
      an oracle year reached through a position-10 candidate simply will not
      stick. **This is not evidence of anything** and must never be read as a
      clean "not this class": the probe did not run. Reporting it as a negative
      is how 182 VINs sat in the parity backlog misfiled as decoder bugs.
    - `NOT_THIS_CLASS` — the pin stuck and a real difference survived it.
    - `COLLAPSED` — the pin stuck and everything left sits inside one stale cell.
    """
    year = oracle_model_year(oracle_rows)
    if year is None:
        return NO_YEAR_FLIP
    mine = _decode(vin, year)
    if mine.get("model_year") != year:
        return PIN_DID_NOT_TAKE
    repinned = fingerprint(diff_rows(oracle_rows, ultravin_rows(mine)))
    if is_expected_divergence(vin, repinned, {"model_year": year}, cells):
        return COLLAPSED
    return NOT_THIS_CLASS


# ------------------------------------------------------------------ the counterfactual

_DECODE = "select * from vpic.spvindecode(%s)"
_CACHED = 'select year, position, "char" from vpic.wmiyearvalidchars where wmi = %s'
_RECOMPUTE = "select p, c from vpic.fextractvalidcharsperwmiyear(%s, %s::smallint)"
_DROP_CELL = "delete from vpic.wmiyearvalidchars where wmi = %s and year = %s"
_FILL_CELL = (
    'insert into vpic.wmiyearvalidchars (id, wmi, year, position, "char") '
    "select %s - row_number() over (), %s, %s, p, c from unnest(%s::int[], %s::varchar[]) as t(p, c)"
)

# Decodes per rolled-back transaction. The stock procs create and drop nine temp
# tables per decode and hold every one of those locks until the transaction ends,
# so an unbounded batch exhausts the shared lock table; the rollback releases
# them. Small enough to stay polite beside other users of the same instance.
COUNTERFACTUAL_BATCH = 200


def _cached_cells(conn: Any, wmi: str) -> dict[int, set[tuple[int, str]]]:
    """What the shipped cache holds for one WMI: year -> {(position, char)}."""
    out: dict[int, set[tuple[int, str]]] = {}
    with conn.cursor() as cur:
        cur.execute(_CACHED, (wmi,))
        for row in cur.fetchall():
            out.setdefault(int(row["year"]), set()).add((int(row["position"]), row["char"]))
    return out


def stale_cells_of(
    conn: Any,
    wmis: list[str],
    cells: dict[tuple[str, int], frozenset[int]] | None = None,
) -> tuple[dict[tuple[str, int], list[tuple[int, str]]], list[str]]:
    """What freshening these WMIs would change, and how that drifts from the list.

    Returns the recomputed contents of every cell whose cache contradicts
    `fExtractValidCharsPerWmiYear` — the ground truth the cache is a stale
    materialisation of, and the same function the proc itself falls back to —
    together with the ways that set disagrees with `scripts/stale_cache_cells.json`.

    The drift check is the audit that makes the counterfactual trustworthy. Both
    directions are failures and both are reported: a cell that differs but is not
    listed means the committed list under-reports the defect and an excuse would
    be resting on an unrecorded one; a listed cell that does not differ means the
    list describes some other dump than the one loaded.

    Writes nothing, and much prefers an autocommit connection: every
    `fExtractValidCharsPerWmiYear` call creates and drops a temp table, and
    thousands of those inside one transaction hold thousands of locks and cost
    about four times as much per call. On a transactional connection it ends each
    WMI with a rollback for that reason — free, because there is nothing to undo.
    """
    listed = {(w, y) for w, y in (load_cells() if cells is None else cells) if w in set(wmis)}
    stale: dict[tuple[str, int], list[tuple[int, str]]] = {}
    for wmi in wmis:
        with conn.cursor() as cur:
            for year, have in _cached_cells(conn, wmi).items():
                cur.execute(_RECOMPUTE, (wmi, year))
                # Deduplicated: the function returns one row per pattern that
                # allows a character, and the proc reads it through SELECT
                # DISTINCT. A cell of 1,449 raw rows is ~100 distinct ones.
                fresh = sorted({(int(r["p"]), r["c"]) for r in cur.fetchall()})
                if set(fresh) != have:
                    stale[(wmi, year)] = fresh
        if not conn.autocommit:
            conn.rollback()
    drift = []
    for what, cell_set in (("not listed as stale", set(stale) - listed), ("listed but not stale", listed - set(stale))):
        if cell_set:
            drift.append(f"{len(cell_set):,} cell(s) {what}: {sorted(cell_set)[:10]}")
    return stale, drift


def counterfactual_rows(
    conn: Any,
    vins: list[str],
    stale: dict[tuple[str, int], list[tuple[int, str]]],
    batch: int = COUNTERFACTUAL_BATCH,
) -> Any:
    """Yield `(vin, canonical rows)` for each VIN decoded against a freshened cache.

    The experiment the class's registration rests on, run per VIN: replace the
    stale cells with what the dump's own pattern rows say they should hold, ask
    the oracle again, and let the caller compare that answer with ultravin's. No
    model of the proc's branch logic is involved, which is what makes it able to
    recognise the divergences a printed-position test cannot — an error count
    that flipped a branch, a model year that moved — and what makes it fail
    closed: whatever the freshened oracle still disagrees about is, by
    construction, not something the cache explains.

    Every batch runs in a transaction that is **always rolled back**, so a shared
    oracle is never left mutated and no other session can even observe the change.
    `conn` must therefore not be in autocommit. Ids are written negative: the
    table's primary key needs one, and drawing from its sequence would advance
    that sequence past the rollback — the one piece of state a rollback does not
    restore.
    """
    if conn.autocommit:
        msg = "counterfactual_rows needs a transactional connection — it rolls its writes back"
        raise ValueError(msg)
    for start in range(0, len(vins), batch):
        chunk = vins[start : start + batch]
        wmis = {vin_wmi(v) for v in chunk}
        mine = [(cell, rows) for cell, rows in stale.items() if cell[0] in wmis]
        try:
            with conn.cursor() as cur:
                first_id = 0
                for (wmi, year), rows in mine:
                    cur.execute(_DROP_CELL, (wmi, year))
                    cur.execute(_FILL_CELL, (first_id, wmi, year, [p for p, _ in rows], [c for _, c in rows]))
                    first_id -= len(rows)
                for vin in chunk:
                    cur.execute(_DECODE, (vin,))
                    yield vin, [from_oracle(r) for r in cur.fetchall()]
        finally:
            conn.rollback()


# --------------------------------------------------------------------------- cli


def expected_in_sweep(report: dict[str, Any]) -> list[str]:
    """The diverging sweep VINs whose divergence is this class."""
    return sorted({e["vin"] for e in report.get("examples", []) if is_expected_divergence(e["vin"], e)})


def expected_in_corpus(corpus: dict[str, Any]) -> list[str]:
    """The diverging frozen-corpus VINs whose frozen difference is this class."""
    return sorted({e["vin"] for e in corpus.get("entries", []) if is_expected_divergence(e["vin"], e["expected_diff"])})


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("cells", help="regenerate the cell list from a --stale-cache-report scan")
    c.add_argument("--report", required=True, help="the scan's JSON report")
    c.add_argument("--out", default=str(CELLS), help="cell list to write")
    e = sub.add_parser("expected", help="VINs whose divergence is the known stale-cache class")
    e.add_argument("--sweep", default="", help="a scripts.parity.sweep report")
    e.add_argument("--corpus", default="", help="tests/parity_corpus.json")
    e.add_argument("--out", default="-", help="JSON output (default stdout)")
    args = ap.parse_args(argv)

    if args.cmd == "cells":
        doc = write_cells(json.loads(Path(args.report).read_text()), Path(args.out))
        problems = consistency_errors(doc)
        print(f"{len(doc['cells'])} stale cells ({doc['dump']}) -> {args.out}", file=sys.stderr)
        for problem in problems:
            print(f"INCONSISTENT: {problem}", file=sys.stderr)
        return 1 if problems else 0

    payload = {
        "sweep": expected_in_sweep(json.loads(Path(args.sweep).read_text())) if args.sweep else [],
        "corpus": expected_in_corpus(json.loads(Path(args.corpus).read_text())) if args.corpus else [],
    }
    text = json.dumps(payload, indent=2) + "\n"
    if args.out == "-":
        print(text, end="")
    else:
        Path(args.out).write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
